# Generated by Django 2.2.2 on 2019-06-21 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats_users',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
