# Generated by Django 2.2.2 on 2019-06-22 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_auto_20190621_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats_users',
            name='id_chat',
            field=models.ForeignKey(null=True, on_delete=False, to='chats.Chats', verbose_name='чат'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id_chat',
            field=models.ForeignKey(null=True, on_delete=False, to='chats.Chats', verbose_name='чат'),
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
    ]
