# Generated by Django 2.2.2 on 2019-06-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_auto_20190624_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='us_check',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chats_users',
            name='id_chat',
            field=models.ForeignKey(null=True, on_delete=False, to='chats.Chats', verbose_name='чат'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id_chat',
            field=models.ForeignKey(null=True, on_delete=False, to='chats.Chats', verbose_name='чат'),
        ),
    ]
